openapi: 3.1.0
info:
  version: 1.0.0
  title: My Application
  description: A modern API for managing contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: API for managing contacts
servers:
  - url: https://nodejs-hw-mongodb-35q8.onrender.com
    description: Production server
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
components:
  schemas:
    $ref: ../swagger/components/schemas.yaml
  responses:
    $ref: ../swagger/components/responses.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
