openapi: 3.1.0
info:
  version: 1.0.0
  title: My Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: A modern API for managing contacts
tags:
  - name: Contacts
    description: API for managing contacts
servers:
  - url: https://nodejs-hw-mongodb-35q8.onrender.com
    description: Production server
paths:
  /contacts:
    get:
      tags: [Contacts]
      summary: Get a list of contacts
      operationId: getContacts
      parameters:
        - name: page
          in: query
          description: Page number (default: 1)
          schema:
            type: integer
            example: 1
        - name: pageSize
          in: query
          description: Number of contacts per page (default: 10)
          schema:
            type: integer
            example: 10
        - name: sortBy
          in: query
          description: Field to sort by (e.g., name, email)
          schema:
            type: string
            example: name
        - name: sortOrder
          in: query
          description: Sort order (asc/desc)
          schema:
            type: string
            enum: [asc, desc]
            example: asc
      responses:
        200:
          description: List of contacts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          description: Internal server error
    post:
      tags: [Contacts]
      summary: Create a new contact
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        201:
          description: Contact created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        400:
          description: Bad request
        500:
          description: Internal server error
  /contacts/{contactId}:
    get:
      tags: [Contacts]
      summary: Get a contact by ID
      operationId: getContactById
      parameters:
        - name: contactId
          in: path
          required: true
          description: The unique ID of the contact
          schema:
            type: string
      responses:
        200:
          description: Contact retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          description: Internal server error
    patch:
      tags: [Contacts]
      summary: Update a contact by ID
      operationId: updateContactById
      parameters:
        - name: contactId
          in: path
          required: true
          description: The unique ID of the contact
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string, description: Name of the contact }
                email: { type: string, description: Email of the contact }
                phone: { type: string, description: Phone number of the contact }
      responses:
        200:
          description: Contact updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          description: Internal server error
    delete:
      tags: [Contacts]
      summary: Delete a contact by ID
      operationId: deleteContactById
      parameters:
        - name: contactId
          in: path
          required: true
          description: The unique ID of the contact
          schema:
            type: string
      responses:
        200:
          description: Contact deleted successfully
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the contact
        name:
          type: string
          description: Name of the contact
        email:
          type: string
          description: Email of the contact
        phone:
          type: string
          description: Phone number of the contact
  responses:
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Contact not found
    Unauthorized:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized access
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
